name: form_bloc_web
description: Easy Form State Management using BLoC pattern. Separate the Form State and Business Logic from the User Interface.
version: 1.1.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  #  form_bloc:
  #    path: ../packages/form_bloc
  #  flutter_form_bloc:
  #    path: ../packages/flutter_form_bloc
  flutter_form_bloc:
    git:
      url: https://github.com/aaassseee/form_bloc.git
      path: packages/flutter_form_bloc
  animations: ">=2.0.2 <3.0.0"
  flutter_syntax_view: ">=4.0.0 <5.0.0"
  flash: ">=1.5.2 <2.0.0"
  url_launcher: ">=6.0.2 <7.0.0"
  flutter_markdown: ">=0.6.10 <1.0.0"
  auto_size_text: ">=3.0.0-nullsafety.0 <4.0.0"
  liquid_progress_indicator: ">=0.4.0 <1.0.0"
  rxdart: ">=0.27.0 <1.0.0"
  google_fonts: ">=2.3.2 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.0 <4.0.0"

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
        - asset: assets/fonts/JosefinSans-Bold.ttf
          weight: 700
  assets:
    - lib/examples/
