name: flutter_form_bloc
description: Create Beautiful Forms in Flutter. The easiest way to Prefill, Async Validation, Update Form Fields, and Show Progress, Failures or Navigate by Reacting to the Form State.
version: 0.30.9
homepage: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
repository: https://github.com/GiancarloCode/form_bloc/tree/master/packages/flutter_form_bloc
issue_tracker: https://github.com/GiancarloCode/form_bloc/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ">=8.0.1 <9.0.0"
  #  form_bloc:
  #    path: ../form_bloc
  #  form_bloc: ^0.30.0
  form_bloc:
    git:
      url: https://github.com/THE-GULU/form_bloc.git
      path: packages/form_bloc
  equatable: ">=2.0.5 <3.0.0"
  rxdart: ">=0.27.5 <1.0.0"
  flutter_keyboard_visibility: ">=6.0.0 <7.0.0"
  collection: ">=1.16.0 <2.0.0"
  intl: ">=0.17.0 <1.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ">=3.0.0 <4.0.0"
